# TEMPLATE
Reroll can convert {Q1}% of supported wheels into semantically equivalent repodata.

## What constitutes a supported wheel?
Reroll supports {Q2}% of all wheels on pypi. As an aspiration, reroll aims to support any wheel you could run by taking a conda environment from the modern supported platforms (linux-64, linux-aarch4, osx-64, osx-arm64, win-64, win-arm64) and then pip or uv would generally dry-run install the wheel (assuming its dependencies are met).

Since this would involve downloading and installing a lot of (perhaps dodgy) wheels, instead, reroll has the following rules that approximate this level of support
* The wheel must be target python 3.4 and up
* It must support CPython (not pypy or other interpreters)
* It must have a valid wheel filename, and metadata
* Older metadata (conforming to previous PEP specs or otherwise) are allowed if they are repairable by uv repair mechanisms
* The metadata must be syntactically valid and consistent with other metadata, as well as the filename
* Wheels targeting linux must be modern, manylinux-based.

When reroll encounters an unsupported wheel, it raises a RerollScopeError for reroll's policy decisions (python 3.4, platform, manylinux etc), or a RerollInvalidWheel error for parsing or semantic problems with the metadata. Reroll considers any parsing error fatal and will not skip or suppress partial failures.

Unsupported wheels fall into these buckets

{Q3: Category, sub category, description, percentage (of all wheels, such that the total is {O2})}

## What errors do unconvertable wheels encounter?
In total, {Q4} wheels are supported, but cannot be converted, and receive a `RerollUnconvertableError`. These errors break down into the following buckets:

{Q5: Sub category, description, total count percentage (of all supported wheels)}

Reroll can convert 99.9% of supported wheels into semantically equivalent repodata.

## What constitutes a supported wheel?
Reroll supports 86.1% of all wheels on pypi. As an aspiration, reroll aims to support any wheel you could run by taking a conda environment from the modern supported platforms (linux-64, linux-aarch4, osx-64, osx-arm64, win-64, win-arm64) and then pip or uv would generally dry-run install the wheel (assuming its dependencies are met).

Since this would involve downloading and installing a lot of (perhaps dodgy) wheels, instead, reroll has the following rules that approximate this level of support
* The wheel must be target python 3.4 and up
* It must support CPython (not pypy or other interpreters)
* It must have a valid wheel filename, and metadata
* Older metadata (conforming to previous PEP specs or otherwise) are allowed if they are repairable by uv repair mechanisms
* The metadata must be syntactically valid and consistent with other metadata, as well as the filename
* Wheels targeting linux must be modern, manylinux-based.

When reroll encounters an unsupported wheel, it raises a RerollScopeError for reroll's policy decisions (python 3.4, platform, manylinux etc), or a RerollInvalidWheel error for parsing or semantic problems with the metadata. Reroll considers any parsing error fatal and will not skip or suppress partial failures.

Unsupported wheels fall into these buckets (13.9% of all wheels, all figures below are % of ALL wheels):

| category | sub category | description | % of all wheels |
|---|---|---|---|
| scope | `UnsupportedPlatformError` | Wheel's platform tag is out of policy scope (e.g. musllinux, 32-bit Windows/Linux, iOS/Android, wasm, non-manylinux glibc, or an unsupported CPU arch) | 9.605% |
| invalid | `InvalidInterpreterTagError` | Wheel filename has a malformed/unrecognized interpreter tag (e.g. PyPy `pp37`) | 2.228% |
| scope | `UnsupportedInterpreterError` | Wheel targets a non-CPython interpreter major (e.g. `py2`, no CPython tag at all) | 1.472% |
| invalid | `PythonRangeMismatchError` | Wheel filename's implied CPython version range doesn't intersect the sdist's declared `Requires-Python` | 0.246% |
| invalid | `InvalidPythonRequirementRangeError` | `Requires-Python` is not a contiguous Python 3.x minor-version range (e.g. `==2.7`) | 0.204% |
| invalid | `InvalidRequirementError` | A `Requires-Dist` entry fails to parse as a PEP 508 requirement string | 0.059% |
| scope | `UnsupportedInterpreterVersionError` | Wheel targets CPython < 3.4 (below reroll's minimum supported version) | 0.044% |
| invalid | `MetadataFilenameMismatchError` | METADATA's Name/Version disagrees with the wheel filename's Name/Version | 0.011% |
| invalid | `InvalidVersionSpecifierError` | A version specifier fails to parse as PEP 440 (e.g. `>-3.6`) | 0.008% |
| invalid | `InvalidAbiTagError` | Wheel filename has a malformed/unrecognized ABI tag | 0.006% |
| invalid | `InvalidFilenameError` | Wheel filename doesn't parse at all (wrong number of `-`-separated parts, etc.) | 0.002% |
| invalid | `InvalidMetadataError` | METADATA fails pydantic validation (e.g. an unparseable `Version:` field) | 0.000% |

## What errors do unconvertable wheels encounter?
In total, 11,139 wheels are supported, but cannot be converted, and receive a `RerollUnconvertableError`. These errors break down into the following buckets (figures below are % of ALL SUPPORTED wheels, 10,438,583 total; the whole bucket is only 0.11% of supported wheels):

| sub category | description | % of all supported wheels |
|---|---|---|
| `UnconvertableRequirementError` | PEP 440 local version label (torch/ipex-llm/vllm-cpu `+cpu`/`+xpu` hardware variants) | 0.061% |
| `InvalidCondaNameError` | name >64 chars (SEO-spam PyPI project names) | 0.012% |
| `UnconvertableRequirementError` | illegal conda extra name (CEP-29) | 0.006% |
| `UnconvertableMarkerError` | unsupported comparator (`~=`) for `python_version(_full)` | 0.006% |
| `UnconvertableMarkerError` | `python_version` literal not a valid version (e.g. `'2.7.*'`, `'3.x'`, `'dev'`) | 0.006% |
| `UnconvertableMarkerError` | unpermitted key (`platform_release`/`_version`/`_machine`/`sys_platform`/`platform_python_implementation`) | 0.005% |
| `UnconvertableRequirementError` | `amulet-compiler-version` numeric-overflow version | 0.004% |
| `UnconvertableMarkerError` | `python_version` literal not major.minor precision | 0.002% |
| `UnconvertableMarkerError` | `in`/`not in` marker unsupported (no matchspec equivalent to set membership) | 0.002% |
| `UnconvertablePythonVersionEqualityError` | `python_version ==`/`!=` a non-major.minor literal | 0.001% |
| `UnconvertableRequirementError` | direct URL reference | 0.001% |
| `UnresolvedCondaNameError` | 4 unresolved dep names (`alchemiscale`, `oasis`, `nr-config`, `sktools`) | 0.000% |
| `InvalidCondaNameError` | homoglyph/Cyrillic lookalike name (`taаmo`) | 0.000% |

## Data setup

Connect to `data/v.db` (read-only) and pull the aggregate counts needed to
answer the questions above. `repodata_conversion` has one row per (project,
wheel filename) pair reroll has synced; `reroll_error` is `NULL` on success,
or a `"<category>: <ExceptionType>: <message>"` string where category is one
of `scope` (deliberately out-of-scope wheel), `invalid` (malformed wheel/metadata),
`unconvertable` (in-scope, valid, but not representable as a matchspec), or
`unexpected` (a bug). "Supported" = not `scope`; "convertible" = success
(`reroll_error IS NULL`).

In [1]:
import sqlite3
import re
import pandas as pd

DB_PATH = "/Users/anil/code/reroll-data/data/v.db"


def query(sql, params=()):
    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    try:
        return pd.read_sql_query(sql, con, params=params)
    finally:
        con.close()


# Top-level category breakdown (cheap: just a CASE/COUNT over the whole table,
# no row hydration).
category_counts = query(
    """
    SELECT
        CASE
            WHEN reroll_error IS NULL THEN 'success'
            WHEN reroll_error LIKE 'scope:%' THEN 'scope'
            WHEN reroll_error LIKE 'invalid:%' THEN 'invalid'
            WHEN reroll_error LIKE 'unconvertable:%' THEN 'unconvertable'
            WHEN reroll_error LIKE 'unexpected:%' THEN 'unexpected'
            ELSE 'other/unrecognized'
        END AS category,
        COUNT(*) AS n
    FROM repodata_conversion
    GROUP BY category
    """
)
total = category_counts["n"].sum()
category_counts["pct_of_all"] = (category_counts["n"] / total * 100).round(2)
print(f"total rows (all wheels reroll has synced): {total:,}")
category_counts.sort_values("n", ascending=False)

total rows (all wheels reroll has synced): 12,121,854

             category         n  pct_of_all
3             success  10427119       86.02
2               scope   1348030       11.12
0             invalid    335241        2.77
4       unconvertable     11139        0.09
1  other/unrecognized       280        0.00
5          unexpected        45        0.00

In [2]:
# The "success" bucket above (reroll_error IS NULL) conflates two things per
# the schema comments: rows reroll has actually converted successfully
# (reroll_data IS NOT NULL) vs. rows not yet attempted at all (reroll_data IS
# NULL AND reroll_error IS NULL). Also check the 280 "other/unrecognized"
# rows -- what do those reroll_error strings actually look like?
status_counts = query(
    """
    SELECT
        CASE
            WHEN reroll_error IS NULL AND reroll_data IS NOT NULL THEN 'success'
            WHEN reroll_error IS NULL AND reroll_data IS NULL THEN 'not_yet_attempted'
            WHEN reroll_error LIKE 'scope:%' THEN 'scope'
            WHEN reroll_error LIKE 'invalid:%' THEN 'invalid'
            WHEN reroll_error LIKE 'unconvertable:%' THEN 'unconvertable'
            WHEN reroll_error LIKE 'unexpected:%' THEN 'unexpected'
            ELSE 'other/unrecognized'
        END AS status,
        COUNT(*) AS n
    FROM repodata_conversion
    GROUP BY status
    """
)
status_counts["pct_of_all"] = (status_counts["n"] / total * 100).round(2)
print(status_counts.sort_values("n", ascending=False).to_string(index=False))
print()
other = query(
    "SELECT reroll_error, COUNT(*) AS n FROM repodata_conversion "
    "WHERE reroll_error IS NOT NULL AND reroll_error NOT LIKE 'scope:%' "
    "AND reroll_error NOT LIKE 'invalid:%' AND reroll_error NOT LIKE 'unconvertable:%' "
    "AND reroll_error NOT LIKE 'unexpected:%' GROUP BY reroll_error ORDER BY n DESC LIMIT 10"
)
other

            status        n  pct_of_all
           success 10427119       86.02
             scope  1348030       11.12
           invalid   335241        2.77
     unconvertable    11139        0.09
other/unrecognized      280        0.00
        unexpected       45        0.00

                                        reroll_error    n
0  unavailable: MetadataUnavailable: wheel has no...  279
1  unavailable: MetadataUnavailable: metadata_blo...    1

In [5]:
# Confirms: reroll_error IS NULL rows are all real successes (reroll_data is
# never NULL when reroll_error is NULL -- no "not yet attempted" rows exist).
# The 280 "other/unrecognized" rows are `unavailable: MetadataUnavailable:...`
# (a data-completeness gap, not a reroll classification -- excluded below).
#
# Definitions (matching reroll's own taxonomy in reroll.errors /
# docs/errors_and_logging.md):
#   unsupported  = scope + invalid   (RerollScopeError / RerollInvalidWheelError)
#   supported    = total - unsupported = success + unconvertable + unexpected + unavailable
#   Q1: % of supported wheels reroll CAN convert  = success / supported
#   Q2: % of all wheels reroll supports            = supported / total
#   O2: % of all wheels reroll does NOT support    = unsupported / total  (100 - Q2)
#   Q4: count of supported-but-unconvertable wheels = unconvertable
#   Q5 buckets: % of ALL SUPPORTED wheels (not just % of the unconvertable slice)
n_success = int(category_counts.loc[category_counts.category == "success", "n"].iloc[0])
n_scope = int(category_counts.loc[category_counts.category == "scope", "n"].iloc[0])
n_invalid = int(category_counts.loc[category_counts.category == "invalid", "n"].iloc[0])
n_unconvertable = int(
    category_counts.loc[category_counts.category == "unconvertable", "n"].iloc[0]
)
n_unexpected = int(
    category_counts.loc[category_counts.category == "unexpected", "n"].iloc[0]
)
n_unavailable = int(
    category_counts.loc[category_counts.category == "other/unrecognized", "n"].iloc[0]
)

n_unsupported = n_scope + n_invalid
n_supported = total - n_unsupported
assert n_supported == n_success + n_unconvertable + n_unexpected + n_unavailable

Q1 = n_success / n_supported * 100
Q2 = n_supported / total * 100
O2 = n_unsupported / total * 100
Q4 = n_unconvertable

print(f"total wheels synced:        {total:>12,}")
print(f"  unsupported (scope+invalid): {n_unsupported:>10,}  ({O2:.2f}% = O2)")
print(f"  supported:                   {n_supported:>10,}  ({Q2:.2f}% = Q2)")
print(f"    success:                   {n_success:>10,}  ({Q1:.4f}% of supported = Q1)")
print(f"    unconvertable:              {n_unconvertable:>10,}  (Q4)")
print(f"    unexpected (bugs):          {n_unexpected:>10,}")
print(f"    unavailable (data gap):     {n_unavailable:>10,}")

total wheels synced:          12,121,854
  unsupported (scope+invalid):  1,683,271  (13.89% = O2)
  supported:                   10,438,583  (86.11% = Q2)
    success:                   10,427,119  (99.8902% of supported = Q1)
    unconvertable:                  11,139  (Q4)
    unexpected (bugs):                  45
    unavailable (data gap):            280

### Q3: what makes up the {O2}% of "unsupported" wheels

`scope` (deliberate policy exclusions) + `invalid` (malformed wheel/metadata)
errors, broken into exception-type sub-buckets. Uses a SQLite UDF to split
`"{category}: {ExcType}: {message}"` in a single pass over the table (12.1M
rows, one scan) rather than loading everything into pandas -- same technique
as `reroll_v0.1.0_failure_analysis.ipynb` section 2.

In [6]:
import re

_ERR_RE = re.compile(r"^([a-z_]+): ([A-Za-z_][A-Za-z0-9_.]*): (.*)$", re.DOTALL)


def _exc_type(e):
    if e is None:
        return None
    m = _ERR_RE.match(e)
    return m.group(2) if m else "UNPARSEABLE"


con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
con.create_function("err_exc_type", 1, _exc_type, deterministic=True)
scope_invalid_types = pd.read_sql_query(
    """
    SELECT
        CASE WHEN reroll_error LIKE 'scope:%' THEN 'scope' ELSE 'invalid' END AS category,
        err_exc_type(reroll_error) AS exc_type,
        COUNT(*) AS n
    FROM repodata_conversion
    WHERE reroll_error LIKE 'scope:%' OR reroll_error LIKE 'invalid:%'
    GROUP BY category, exc_type
    ORDER BY n DESC
    """,
    con,
)
con.close()
scope_invalid_types["pct_of_all_wheels"] = (
    scope_invalid_types["n"] / total * 100
).round(3)
print(f"sum of n: {scope_invalid_types['n'].sum():,} (should equal {n_unsupported:,})")
scope_invalid_types

sum of n: 1,683,271 (should equal 1,683,271)

   category                            exc_type        n  pct_of_all_wheels
0     scope            UnsupportedPlatformError  1164312              9.605
1   invalid          InvalidInterpreterTagError   270048              2.228
2     scope         UnsupportedInterpreterError   178422              1.472
3   invalid            PythonRangeMismatchError    29861              0.246
4   invalid  InvalidPythonRequirementRangeError    24741              0.204
5   invalid             InvalidRequirementError     7187              0.059
6     scope  UnsupportedInterpreterVersionError     5296              0.044
7   invalid       MetadataFilenameMismatchError     1342              0.011
8   invalid        InvalidVersionSpecifierError      992              0.008
9   invalid                  InvalidAbiTagError      778              0.006
10  invalid                InvalidFilenameError      239              0.002
11  invalid                InvalidMetadataError       53              0.000

In [7]:
# One representative message per exc_type, to write accurate human
# descriptions for the Q3 table (single window-function pass, same scan cost
# as the previous cell -- not a second full table scan of the whole 12.1M-row
# table, just this filtered 1.68M-row slice).
con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
con.create_function("err_exc_type", 1, _exc_type, deterministic=True)
samples = pd.read_sql_query(
    """
    WITH ranked AS (
        SELECT
            err_exc_type(reroll_error) AS exc_type,
            reroll_error,
            ROW_NUMBER() OVER (PARTITION BY err_exc_type(reroll_error) ORDER BY project, filename) AS rn
        FROM repodata_conversion
        WHERE reroll_error LIKE 'scope:%' OR reroll_error LIKE 'invalid:%'
    )
    SELECT exc_type, reroll_error FROM ranked WHERE rn = 1
    """,
    con,
)
con.close()
pd.set_option("display.max_colwidth", 300)
samples

,exc_type,reroll_error
0,InvalidAbiTagError,invalid: InvalidAbiTagError: invalid abi tag: 'py3'
1,InvalidFilenameError,invalid: InvalidFilenameError: unparseable wheel filename '101903751_topsis-py3-none-any.whl': Invalid wheel filename (wrong number of parts): '101903751_topsis-py3-none-any'
2,InvalidInterpreterTagError,invalid: InvalidInterpreterTagError: invalid interpreter tag: 'pp37'
3,InvalidMetadataError,"invalid: InvalidMetadataError: invalid METADATA: 1 validation error for WheelMetadata\nversion\n Value error, Invalid version: '0.2.1.Perceval' [type=value_error, input_value='0.2.1.Perceval', input_type=str]\n For further information visit https://errors.pydantic.dev/2.13/v/value_error"
4,InvalidPythonRequirementRangeError,invalid: InvalidPythonRequirementRangeError: not a contiguous Python 3.x minor range: ==2.7
5,InvalidRequirementError,"invalid: InvalidRequirementError: invalid requirement 'python-slugify (==4.0.1requests==2.24.0)': Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier\n python-slugify (==4.0.1requests==2.24.0)\n ~~~~~~~~~^"
6,InvalidVersionSpecifierError,invalid: InvalidVersionSpecifierError: invalid version specifier '>-3.6': Invalid specifier: '>-3.6'
7,MetadataFilenameMismatchError,invalid: MetadataFilenameMismatchError: METADATA Name/Version ('aksharajaana' 0.1.9.3) does not match filename 'AksharaJaana-0.1.9.4-py3-none-any.whl' ('aksharajaana' 0.1.9.4)
8,PythonRangeMismatchError,"invalid: PythonRangeMismatchError: csf-3dfin: filename-implied python range python >=3.14,<3.15.0a0 does not intersect Requires-Python '<3.14,>=3.10'; no depends generated"
9,UnsupportedInterpreterError,scope: UnsupportedInterpreterError: unsupported interpreter major version: 'py2'
10,UnsupportedInterpreterVersionError,scope: UnsupportedInterpreterVersionError: CPython < 3.4 is unsupported: 'cp33'
11,UnsupportedPlatformError,scope: UnsupportedPlatformError: unsupported platform tag: 'win32'

In [9]:
for _, row in samples.iterrows():
    print(f"=== {row['exc_type']} ===")
    print(row["reroll_error"])
    print()

=== InvalidAbiTagError ===
invalid: InvalidAbiTagError: invalid abi tag: 'py3'

=== InvalidFilenameError ===
invalid: InvalidFilenameError: unparseable wheel filename '101903751_topsis-py3-none-any.whl': Invalid wheel filename (wrong num
ber of parts): '101903751_topsis-py3-none-any'

=== InvalidInterpreterTagError ===
invalid: InvalidInterpreterTagError: invalid interpreter tag: 'pp37'

=== InvalidMetadataError ===
invalid: InvalidMetadataError: invalid METADATA: 1 validation error for WheelMetadata
version
  Value error, Invalid version: '0.2.1.Perceval' [type=value_error, input_value='0.2.1.Perceval', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error

=== InvalidPythonRequirementRangeError ===
invalid: InvalidPythonRequirementRangeError: not a contiguous Python 3.x minor range: ==2.7

=== InvalidRequirementError ===
invalid: InvalidRequirementError: invalid requirement 'python-slugify (==4.0.1requests==2.24.0)': Expected matching RIGHT_PARENT
HESIS for LEFT_PARENTHESIS, after version specifier
    python-slugify (==4.0.1requests==2.24.0)
                   ~~~~~~~~~^

=== InvalidVersionSpecifierError ===
invalid: InvalidVersionSpecifierError: invalid version specifier '>-3.6': Invalid specifier: '>-3.6'

=== MetadataFilenameMismatchError ===
invalid: MetadataFilenameMismatchError: METADATA Name/Version ('aksharajaana' 0.1.9.3) does not match filename 'AksharaJaana-0.1
.9.4-py3-none-any.whl' ('aksharajaana' 0.1.9.4)

=== PythonRangeMismatchError ===
invalid: PythonRangeMismatchError: csf-3dfin: filename-implied python range python >=3.14,<3.15.0a0 does not intersect Requires-
Python '<3.14,>=3.10'; no depends generated

=== UnsupportedInterpreterError ===
scope: UnsupportedInterpreterError: unsupported interpreter major version: 'py2'

=== UnsupportedInterpreterVersionError ===
scope: UnsupportedInterpreterVersionError: CPython < 3.4 is unsupported: 'cp33'

=== UnsupportedPlatformError ===
scope: UnsupportedPlatformError: unsupported platform tag: 'win32'

### Q3 table: human descriptions for each unsupported sub-bucket

One representative `reroll_error` message per exc_type (above) is enough to
write an accurate one-line description for each -- no further sampling
needed.

In [10]:
descriptions = {
    "UnsupportedPlatformError": "Wheel's platform tag is out of policy scope (e.g. musllinux, 32-bit Windows/Linux, iOS/Android, wasm, non-manylinux glibc, or an unsupported CPU arch)",
    "InvalidInterpreterTagError": "Wheel filename has a malformed/unrecognized interpreter tag (e.g. PyPy `pp37`)",
    "UnsupportedInterpreterError": "Wheel targets a non-CPython interpreter major (e.g. `py2`, no CPython tag at all)",
    "PythonRangeMismatchError": "Wheel filename's implied CPython version range doesn't intersect the sdist's declared `Requires-Python`",
    "InvalidPythonRequirementRangeError": "`Requires-Python` is not a contiguous Python 3.x minor-version range (e.g. `==2.7`)",
    "InvalidRequirementError": "A `Requires-Dist` entry fails to parse as a PEP 508 requirement string",
    "UnsupportedInterpreterVersionError": "Wheel targets CPython < 3.4 (below reroll's minimum supported version)",
    "MetadataFilenameMismatchError": "METADATA's Name/Version disagrees with the wheel filename's Name/Version",
    "InvalidVersionSpecifierError": "A version specifier fails to parse as PEP 440 (e.g. `>-3.6`)",
    "InvalidAbiTagError": "Wheel filename has a malformed/unrecognized ABI tag",
    "InvalidFilenameError": "Wheel filename doesn't parse at all (wrong number of `-`-separated parts, etc.)",
    "InvalidMetadataError": "METADATA fails pydantic validation (e.g. an unparseable `Version:` field)",
}
category_map = dict(
    zip(scope_invalid_types["exc_type"], scope_invalid_types["category"])
)

q3 = scope_invalid_types.copy()
q3["description"] = q3["exc_type"].map(descriptions)
q3 = q3[["category", "exc_type", "description", "n", "pct_of_all_wheels"]]
q3 = q3.sort_values("n", ascending=False).reset_index(drop=True)
print(
    f"O2 check: sum of pct_of_all_wheels = {q3['pct_of_all_wheels'].sum():.2f}% (O2 = {O2:.2f}%)"
)
q3

O2 check: sum of pct_of_all_wheels = 13.88% (O2 = 13.89%)

,category,exc_type,description,n,pct_of_all_wheels
0,scope,UnsupportedPlatformError,"Wheel's platform tag is out of policy scope (e.g. musllinux, 32-bit Windows/Linux, iOS/Android, wasm, non-manylinux glibc, or an unsupported CPU arch)",1164312,9.605
1,invalid,InvalidInterpreterTagError,Wheel filename has a malformed/unrecognized interpreter tag (e.g. PyPy `pp37`),270048,2.228
2,scope,UnsupportedInterpreterError,"Wheel targets a non-CPython interpreter major (e.g. `py2`, no CPython tag at all)",178422,1.472
3,invalid,PythonRangeMismatchError,Wheel filename's implied CPython version range doesn't intersect the sdist's declared `Requires-Python`,29861,0.246
4,invalid,InvalidPythonRequirementRangeError,`Requires-Python` is not a contiguous Python 3.x minor-version range (e.g. `==2.7`),24741,0.204
5,invalid,InvalidRequirementError,A `Requires-Dist` entry fails to parse as a PEP 508 requirement string,7187,0.059
6,scope,UnsupportedInterpreterVersionError,Wheel targets CPython < 3.4 (below reroll's minimum supported version),5296,0.044
7,invalid,MetadataFilenameMismatchError,METADATA's Name/Version disagrees with the wheel filename's Name/Version,1342,0.011
8,invalid,InvalidVersionSpecifierError,A version specifier fails to parse as PEP 440 (e.g. `>-3.6`),992,0.008
9,invalid,InvalidAbiTagError,Wheel filename has a malformed/unrecognized ABI tag,778,0.006
10,invalid,InvalidFilenameError,"Wheel filename doesn't parse at all (wrong number of `-`-separated parts, etc.)",239,0.002
11,invalid,InvalidMetadataError,METADATA fails pydantic validation (e.g. an unparseable `Version:` field),53,0.000

### Q4 / Q5: the unconvertable bucket

`notebooks/reroll_v0.2.0_unconvertable_analysis.ipynb` established the
classification regexes for this population back when it was 15,595 rows
(0.2.0). For 0.3.0 the bucket has shrunk further to 11,139 rows -- still
cheap to load in full (a targeted `LIKE 'unconvertable:%'` fetch, not a scan
of the whole 12.1M-row table) -- so re-run the same classification logic
live against the current `data/v.db` rather than reusing copied-verbatim
counts, which silently went stale (and broke the `n == Q4` assertion) the
moment the bucket size changed between releases.

In [16]:
# Load the full "unconvertable" bucket live (small population, cheap
# targeted fetch) and re-run the classification regexes from
# reroll_v0.2.0_unconvertable_analysis.ipynb -- copied-verbatim counts go
# stale as soon as the bucket size changes between releases.
con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
unconvertable_df = pd.read_sql_query(
    "SELECT project, filename, reroll_error FROM repodata_conversion "
    "WHERE reroll_error LIKE 'unconvertable:%'",
    con,
)
con.close()
unconvertable_df["exc_type"] = unconvertable_df["reroll_error"].str.extract(
    r"^unconvertable:\s*(\w+)"
)[0]

# UnconvertableRequirementError sub-buckets
req_errs = unconvertable_df[
    unconvertable_df["exc_type"] == "UnconvertableRequirementError"
].copy()


def classify_req_error(msg):
    m = re.search(r"cannot convert '[^']*':\s*(.+)$", msg)
    if m:
        return m.group(1)
    m = re.search(r"is not a legal conda extra name \(CEP-29\):\s*(.+)$", msg)
    if m:
        return f"illegal conda extra name: {m.group(1)}"
    return "OTHER/unrecognized"


req_errs["reason_template"] = (
    req_errs["reroll_error"]
    .map(classify_req_error)
    .str.replace(r"'[^']*'", "<LIT>", regex=True)
    .str.replace(r"\b\d+(?:\.\d+)*\b", "<NUM>", regex=True)
)
req_sub = req_errs["reason_template"].value_counts()

# UnconvertableMarkerError sub-buckets
marker_errs = unconvertable_df[
    unconvertable_df["exc_type"] == "UnconvertableMarkerError"
].copy()
reason = marker_errs["reroll_error"].str.extract(r"UnconvertableMarkerError:\s*(.+)$")[
    0
]
unpermitted = reason.str.extract(r"unpermitted key\(s\) \['([^']*)'")[0]


def bucket_marker(msg, key):
    if pd.notna(key):
        return "unpermitted key"
    if "markers are not supported" in msg:
        return "'in'/'not in' marker unsupported"
    if "not a valid version" in msg:
        return "python_version literal not a valid version"
    if "is not supported for" in msg:
        return "unsupported comparator (~=) for python_version(_full)"
    if "not a plain major.minor" in msg:
        return "python_version literal not major.minor precision"
    return "OTHER/unrecognized"


marker_errs["bucket"] = [bucket_marker(m, k) for m, k in zip(reason, unpermitted)]
marker_sub = marker_errs["bucket"].value_counts()

# UnresolvedCondaNameError sub-buckets
unres = unconvertable_df[
    unconvertable_df["exc_type"] == "UnresolvedCondaNameError"
].copy()
unres["dep_name"] = unres["reroll_error"].str.extract(
    r"no mapper resolved a conda name for '([^']*)'"
)[0]
unres_sub = unres["dep_name"].value_counts()

# InvalidCondaNameError sub-buckets
invalid_errs = unconvertable_df[unconvertable_df["exc_type"] == "InvalidCondaNameError"]
n_long_names = invalid_errs["reroll_error"].str.contains("exceeds 64 characters").sum()
n_homoglyph = len(invalid_errs) - n_long_names

n_pyver_eq = (
    unconvertable_df["exc_type"] == "UnconvertablePythonVersionEqualityError"
).sum()

q5_rows = [
    (
        "UnconvertableRequirementError",
        "PEP 440 local version label (torch/ipex-llm/vllm-cpu +cpu/+xpu hardware variants)",
        int(req_sub.get("it has a local version label", 0)),
    ),
    (
        "UnconvertableMarkerError",
        "unsupported comparator (~=) for python_version(_full)",
        int(marker_sub.get("unsupported comparator (~=) for python_version(_full)", 0)),
    ),
    (
        "UnconvertableMarkerError",
        "python_version literal not a valid version (e.g. '2.7.*', '3.x', 'dev')",
        int(marker_sub.get("python_version literal not a valid version", 0)),
    ),
    (
        "InvalidCondaNameError",
        "name >64 chars (SEO-spam PyPI project names)",
        int(n_long_names),
    ),
    (
        "UnconvertableMarkerError",
        "unpermitted key (platform_release/_version/_machine/sys_platform/platform_python_implementation)",
        int(marker_sub.get("unpermitted key", 0)),
    ),
    (
        "UnconvertableRequirementError",
        "illegal conda extra name (CEP-29)",
        int(
            req_sub.get(
                "illegal conda extra name: must be <NUM>-<NUM> characters of [a-z0-9_.+-]",
                0,
            )
        ),
    ),
    (
        "UnconvertableMarkerError",
        "python_version literal not major.minor precision",
        int(marker_sub.get("python_version literal not major.minor precision", 0)),
    ),
    (
        "UnconvertablePythonVersionEqualityError",
        "python_version ==/!= a non-major.minor literal",
        int(n_pyver_eq),
    ),
    (
        "UnconvertableMarkerError",
        "'in'/'not in' marker unsupported",
        int(marker_sub.get("'in'/'not in' marker unsupported", 0)),
    ),
    (
        "UnconvertableRequirementError",
        "amulet-compiler-version numeric-overflow version",
        int(req_sub.get("OTHER/unrecognized", 0)),
    ),
    (
        "UnconvertableRequirementError",
        "direct URL reference",
        int(req_sub.get("it has a direct URL reference", 0)),
    ),
    (
        "UnresolvedCondaNameError",
        f"{len(unres_sub)} unresolved dep names ({', '.join(unres_sub.index)})",
        int(unres_sub.sum()),
    ),
    (
        "InvalidCondaNameError",
        "homoglyph/Cyrillic lookalike name (taаmo)",
        int(n_homoglyph),
    ),
]
q5 = pd.DataFrame(q5_rows, columns=["exc_type", "description", "n"])
q5 = q5[q5["n"] > 0].sort_values("n", ascending=False).reset_index(drop=True)

assert q5["n"].sum() == n_unconvertable == Q4, (q5["n"].sum(), n_unconvertable, Q4)
q5["pct_of_supported"] = (q5["n"] / n_supported * 100).round(3)
print(f"Q4 = {Q4:,} rows")
print(
    f"sum of pct_of_supported = {q5['pct_of_supported'].sum():.2f}% "
    f"(should equal Q4/n_supported = {Q4 / n_supported * 100:.2f}%)"
)
q5

Q4 = 11,139 rows
sum of pct_of_supported = 0.11% (should equal Q4/n_supported = 0.11%)

,exc_type,description,n,pct_of_supported
0,UnconvertableRequirementError,PEP 440 local version label (torch/ipex-llm/vllm-cpu +cpu/+xpu hardware variants),6319,0.061
1,InvalidCondaNameError,name >64 chars (SEO-spam PyPI project names),1275,0.012
2,UnconvertableRequirementError,illegal conda extra name (CEP-29),672,0.006
3,UnconvertableMarkerError,unsupported comparator (~=) for python_version(_full),625,0.006
4,UnconvertableMarkerError,"python_version literal not a valid version (e.g. '2.7.*', '3.x', 'dev')",616,0.006
5,UnconvertableMarkerError,unpermitted key (platform_release/_version/_machine/sys_platform/platform_python_implementation),483,0.005
6,UnconvertableRequirementError,amulet-compiler-version numeric-overflow version,416,0.004
7,UnconvertableMarkerError,python_version literal not major.minor precision,239,0.002
8,UnconvertableMarkerError,'in'/'not in' marker unsupported,230,0.002
9,UnconvertablePythonVersionEqualityError,python_version ==/!= a non-major.minor literal,134,0.001
10,UnconvertableRequirementError,direct URL reference,94,0.001
11,UnresolvedCondaNameError,"4 unresolved dep names (alchemiscale, oasis, nr-config, sktools)",34,0.000
12,InvalidCondaNameError,homoglyph/Cyrillic lookalike name (taаmo),2,0.000