# TEMPLATE
Reroll can convert {Q1}% of supported wheels into semantically equivalent repodata.

## What constitutes a supported wheel?
Reroll supports {Q2}% of all wheels on pypi. As an aspiration, reroll aims to support any wheel you could run by taking a conda environment from the modern supported platforms (linux-64, linux-aarch4, osx-64, osx-arm64, win-64, win-arm64) and then pip or uv would generally dry-run install the wheel (assuming its dependencies are met).

Since this would involve downloading and installing a lot of (perhaps dodgy) wheels, instead, reroll has the following rules that approximate this level of support
* The wheel must be target python 3.4 and up
* It must support CPython (not pypy or other interpreters)
* It must have a valid wheel filename, and metadata
* Older metadata (conforming to previous PEP specs or otherwise) are allowed if they are repairable by uv repair mechanisms
* The metadata must be syntactically valid and consistent with other metadata, as well as the filename
* Wheels targeting linux must be modern, manylinux-based.

When reroll encounters an unsupported wheel, it raises a RerollScopeError for reroll's policy decisions (python 3.4, platform, manylinux etc), or a RerollInvalidWheel error for parsing or semantic problems with the metadata. Reroll considers any parsing error fatal and will not skip or suppress partial failures.

Unsupported wheels fall into these buckets

{Q3: Category, sub category, description, percentage (of all wheels, such that the total is {O2})}

## What errors do unconvertable wheels encounter?
In total, {Q4} wheels are supported, but cannot be converted, and receive a `RerollUnconvertableError`. These errors break down into the following buckets:

{Q5: Sub category, description, total count percentage (of all supported wheels)}

Reroll can convert 99.9% of supported wheels into semantically equivalent repodata.

## What constitutes a supported wheel?
Reroll supports 86.2% of all wheels on pypi. As an aspiration, reroll aims to support any wheel you could run by taking a conda environment from the modern supported platforms (linux-64, linux-aarch4, osx-64, osx-arm64, win-64, win-arm64) and then pip or uv would generally dry-run install the wheel (assuming its dependencies are met).

Since this would involve downloading and installing a lot of (perhaps dodgy) wheels, instead, reroll has the following rules that approximate this level of support
* The wheel must be target python 3.4 and up
* It must support CPython (not pypy or other interpreters)
* It must have a valid wheel filename, and metadata
* Older metadata (conforming to previous PEP specs or otherwise) are allowed if they are repairable by uv repair mechanisms
* The metadata must be syntactically valid and consistent with other metadata, as well as the filename
* Wheels targeting linux must be modern, manylinux-based.

When reroll encounters an unsupported wheel, it raises a RerollScopeError for reroll's policy decisions (python 3.4, platform, manylinux etc), or a RerollInvalidWheel error for parsing or semantic problems with the metadata. Reroll considers any parsing error fatal and will not skip or suppress partial failures.

Unsupported wheels fall into these buckets (13.8% of attempted wheels, all figures below are % of ATTEMPTED wheels -- see note below):

| category | sub category | description | % of attempted wheels |
|---|---|---|---|
| scope | `UnsupportedPlatformError` | Wheel's platform tag is out of policy scope (e.g. musllinux, 32-bit Windows/Linux, iOS/Android, wasm, non-manylinux glibc, or an unsupported CPU arch) | 9.576% |
| invalid | `InvalidInterpreterTagError` | Wheel filename has a malformed/unrecognized interpreter tag (e.g. PyPy `pp37`) | 2.190% |
| scope | `UnsupportedInterpreterError` | Wheel targets a non-CPython interpreter major (e.g. `py2`, no CPython tag at all) | 1.453% |
| invalid | `PythonRangeMismatchError` | Wheel filename's implied CPython version range doesn't intersect the sdist's declared `Requires-Python` | 0.246% |
| invalid | `InvalidPythonRequirementRangeError` | `Requires-Python` is not a contiguous Python 3.x minor-version range (e.g. `==2.7`) | 0.202% |
| invalid | `InvalidRequirementError` | A `Requires-Dist` entry fails to parse as a PEP 508 requirement string | 0.058% |
| scope | `UnsupportedInterpreterVersionError` | Wheel targets CPython < 3.4 (below reroll's minimum supported version) | 0.043% |
| invalid | `MetadataFilenameMismatchError` | METADATA's Name/Version disagrees with the wheel filename's Name/Version | 0.011% |
| invalid | `InvalidAbiTagError` | Wheel filename has a malformed/unrecognized ABI tag | 0.008% |
| invalid | `InvalidVersionSpecifierError` | A version specifier fails to parse as PEP 440 (e.g. `>-3.6`) | 0.008% |
| invalid | `InvalidFilenameError` | Wheel filename doesn't parse at all (wrong number of `-`-separated parts, etc.) | 0.002% |
| invalid | `InvalidMetadataError` | METADATA fails pydantic validation (e.g. an unparseable `Version:` field) | 0.000% |

*Note on "attempted": of the 12,344,726 wheel rows `main.db` tracks, 118,637 (0.96%) have not been attempted by reroll's converter yet (backlog on the `wheel_todo` queue) and are excluded from every percentage above -- the attempted 12,226,089 are treated as representative of the full population.*

## What errors do unconvertable wheels encounter?
In total, 11,225 wheels are supported, but cannot be converted, and receive a `RerollUnconvertableError`. These errors break down into the following buckets (figures below are % of ALL SUPPORTED wheels, 10,539,197 total; the whole bucket is only 0.11% of supported wheels):

| sub category | description | % of all supported wheels |
|---|---|---|
| `UnconvertableRequirementError` | PEP 440 local version label (torch/ipex-llm/vllm-cpu `+cpu`/`+xpu` hardware variants) | 0.061% |
| `InvalidCondaNameError` | name >64 chars (SEO-spam PyPI project names) | 0.012% |
| `UnconvertableRequirementError` | illegal conda extra name (CEP-29) | 0.006% |
| `UnconvertableMarkerError` | unsupported comparator (`~=`) for `python_version(_full)` | 0.006% |
| `UnconvertableMarkerError` | `python_version` literal not a valid version (e.g. `'2.7.*'`, `'3.x'`, `'dev'`) | 0.006% |
| `UnconvertableMarkerError` | unpermitted key (`platform_release`/`_version`/`_machine`/`sys_platform`/`platform_python_implementation`) | 0.005% |
| `UnconvertableRequirementError` | `amulet-compiler-version` numeric-overflow version | 0.004% |
| `UnconvertableMarkerError` | `python_version` literal not major.minor precision | 0.002% |
| `UnconvertableMarkerError` | `in`/`not in` marker unsupported (no matchspec equivalent to set membership) | 0.002% |
| `UnconvertablePythonVersionEqualityError` | `python_version ==`/`!=` a non-major.minor literal | 0.001% |
| `UnconvertableRequirementError` | direct URL reference | 0.001% |
| `UnresolvedCondaNameError` | 4 unresolved dep names (`alchemiscale`, `oasis`, `nr-config`, `sktools`) | 0.000% |
| `InvalidCondaNameError` | homoglyph/Cyrillic lookalike name (`tаamo`) | 0.000% |

An earlier pass of this analysis showed a large `MissingPypiCondaStaticMapping` bucket
(reroll's curated-mapping gate rejecting a wheel whose dependency name the live mapper
chain *did* resolve, just not yet promoted into `main.db.pypi_conda_names`) as the
single largest `unconvertable` cause. That gate had a bug, since fixed; with it
corrected, those wheels no longer land in `unconvertable` at all, which is why `Q4`
above (11,225) is roughly half what it was in that earlier pass.

## Data setup

Connect to `data/main.db` (read-only; see `reroll_data.db2`) and pull the aggregate
counts needed to answer the questions above. `wheel` has one row per wheel filename
reroll's crawler has ever recorded; `reroll_data` is non-NULL exactly when reroll
converted that wheel successfully. `reroll_errors` has *at most one* row per wheel that
did **not** convert -- `category` is one of `scope` (deliberately out-of-scope wheel),
`invalid` (malformed wheel/metadata), `unconvertable` (in-scope, valid, but not
representable as a matchspec), `unavailable` (a data-completeness gap, e.g. PEP 658
metadata never fetched), `unexpected` (a bug), or `runtime` (an unstable-environment
error, recorded for accounting only -- see `reroll_data.db2`'s module docstring; it
never settles a wheel and currently has zero rows in this snapshot). A wheel with no
`reroll_errors` row and `reroll_data IS NULL` simply hasn't been attempted yet (backlog
on the `wheel_todo` partial index) -- unlike the legacy `v.db.repodata_conversion` table
this replaced, that state can actually occur now, since `main.db`/`pypi.db` are live and
continuously crawled/converted rather than a one-time migrated snapshot. "Supported" =
not `scope`; "convertible" = success (`reroll_data IS NOT NULL`). Every query below
reads only `main.db` -- `pypi.db` and the legacy `v.db` are never touched.

In [28]:
import sqlite3
import re
import pandas as pd

MAIN_DB_PATH = "/Users/anil/code/reroll-data/data/main.db"


def query_main(sql, params=()):
    con = sqlite3.connect(f"file:{MAIN_DB_PATH}?mode=ro", uri=True)
    try:
        return pd.read_sql_query(sql, con, params=params)
    finally:
        con.close()


# Top-level category breakdown (cheap: a LEFT JOIN + GROUP BY over the whole
# wheel table, no row hydration). A wheel with no `reroll_errors` row has
# either succeeded (`reroll_data IS NOT NULL`) or not yet been attempted --
# same conflation the old `reroll_error IS NULL` bucket had against v.db,
# teased apart in the next cell.
category_counts = query_main(
    """
    SELECT
        COALESCE(e.category, 'success') AS category,
        COUNT(*) AS n
    FROM wheel w
    LEFT JOIN reroll_errors e ON e.wheel_id = w.id
    GROUP BY category
    """
)
total = int(category_counts["n"].sum())
category_counts["pct_of_all"] = (category_counts["n"] / total * 100).round(2)
print(f"total rows (all wheels main.db.wheel has a row for): {total:,}")
category_counts.sort_values("n", ascending=False)

total rows (all wheels main.db.wheel has a row for): 12,344,726

        category         n  pct_of_all
0        success  10646298       86.24
2          scope   1353752       10.97
1        invalid    333140        2.70
4  unconvertable     11225        0.09
3    unavailable       274        0.00
5     unexpected        37        0.00

In [36]:
# The "success" bucket above conflates two things, same as the legacy
# v.db.repodata_conversion analysis: rows reroll has actually converted
# (`reroll_data IS NOT NULL`) vs. rows not yet attempted at all
# (`reroll_data IS NULL`, no `reroll_errors` row -- backlog on the
# `wheel_todo` index). `yanked` is split out separately (not folded into
# `not_yet_attempted`): `reroll_data.reroll_convert`'s own worklist
# (`db2.OUTSTANDING_WHEEL` / the `wheel_todo` partial index) deliberately
# excludes `yanked = 1` rows -- "nothing consumes a yanked wheel's
# `reroll_data` under normal dependency resolution, so it is not worklist
# work" (see `reroll_data.db2`'s `wheel_todo` comment) -- so a yanked wheel
# sits at `reroll_data IS NULL` forever by design, and lumping it into
# `not_yet_attempted` overstated the real backlog by ~118.6k rows (all of
# `not_yet_attempted` turned out to be yanked wheels in this snapshot; see
# the notebook's own diagnosis of that miscount). Also confirm `category`
# never holds anything outside the fixed CHECK enum on `reroll_errors`
# (scope/invalid/unconvertable/unavailable/unexpected/runtime) -- unlike the
# old free-text `reroll_error` column, there is no "other/unrecognized"
# bucket possible here by construction, but check anyway since this is
# live, evolving data.
status_counts = query_main(
    """
    SELECT
        CASE
            WHEN e.category IS NOT NULL THEN e.category
            WHEN w.reroll_data IS NOT NULL THEN 'success'
            WHEN w.yanked = 1 THEN 'yanked'
            ELSE 'not_yet_attempted'
        END AS status,
        COUNT(*) AS n
    FROM wheel w
    LEFT JOIN reroll_errors e ON e.wheel_id = w.id
    GROUP BY status
    """
)
status_counts["pct_of_all"] = (status_counts["n"] / total * 100).round(2)
print(status_counts.sort_values("n", ascending=False).to_string(index=False))

_KNOWN_STATUSES = {
    "scope",
    "invalid",
    "unconvertable",
    "unavailable",
    "unexpected",
    "runtime",
    "success",
    "not_yet_attempted",
    "yanked",
}
_unknown = set(status_counts["status"]) - _KNOWN_STATUSES
assert not _unknown, f"unexpected reroll_errors.category value(s): {_unknown}"

       status        n  pct_of_all
      success 10527661       85.28
        scope  1353752       10.97
      invalid   333140        2.70
       yanked   118637        0.96
unconvertable    11225        0.09
  unavailable      274        0.00
   unexpected       37        0.00

In [37]:
# Definitions (matching reroll's own taxonomy in reroll.errors /
# docs/errors_and_logging.md, now backed directly by
# main.db.reroll_errors.category instead of a parsed text prefix):
#   unsupported  = scope + invalid   (RerollScopeError / RerollInvalidWheelError)
#   attempted    = total - not_yet_attempted - yanked  (wheels reroll has actually classified)
#   supported    = attempted - unsupported = success + unconvertable + unexpected + unavailable + runtime
#   Q1: % of supported wheels reroll CAN convert  = success / supported
#   Q2: % of all wheels reroll supports            = supported / attempted
#   O2: % of all wheels reroll does NOT support    = unsupported / attempted  (100 - Q2)
#   Q4: count of supported-but-unconvertable wheels = unconvertable
#   Q5 buckets: % of ALL SUPPORTED wheels (not just % of the unconvertable slice)
#
# `not_yet_attempted` and `yanked` are both excluded from every denominator
# below -- `not_yet_attempted` is genuine backlog on `wheel_todo` (Q2/O2
# therefore treat the attempted wheels as representative of the full PyPI
# population, a fair assumption while the backlog stays a small, unbiased
# slice -- see the not_yet_attempted % printed below); `yanked` is not
# backlog at all -- `reroll_convert`'s own worklist (`wheel_todo`)
# deliberately never attempts a yanked wheel (see the status_counts cell
# above), so it would never move out of this bucket no matter how many
# `convert` runs happen, and including it in `attempted` would permanently
# understate Q1/Q2. `runtime` (a RerollRuntimeError, recorded for accounting
# only, never settles a wheel -- see `reroll_data.db2`'s module docstring)
# is currently zero rows in this snapshot but is folded into `supported`
# rather than dropped, matching `stats_main`'s own accounting.
def _n(status):
    m = status_counts.loc[status_counts.status == status, "n"]
    return int(m.iloc[0]) if len(m) else 0


n_not_yet_attempted = _n("not_yet_attempted")
n_yanked = _n("yanked")
n_success = _n("success")
n_scope = _n("scope")
n_invalid = _n("invalid")
n_unconvertable = _n("unconvertable")
n_unexpected = _n("unexpected")
n_unavailable = _n("unavailable")
n_runtime = _n("runtime")

attempted = total - n_not_yet_attempted - n_yanked
n_unsupported = n_scope + n_invalid
n_supported = attempted - n_unsupported
assert (
    n_supported
    == n_success + n_unconvertable + n_unexpected + n_unavailable + n_runtime
)

Q1 = n_success / n_supported * 100
Q2 = n_supported / attempted * 100
O2 = n_unsupported / attempted * 100
Q4 = n_unconvertable

print(f"total wheels in main.db.wheel:  {total:>12,}")
print(
    f"  yanked:                        {n_yanked:>10,}  "
    f"({n_yanked / total * 100:.2f}% -- excluded from all % below; "
    "reroll_convert never attempts these by design)"
)
print(
    f"  not yet attempted:            {n_not_yet_attempted:>10,}  "
    f"({n_not_yet_attempted / total * 100:.2f}% -- excluded from all % below)"
)
print(f"attempted:                      {attempted:>12,}")
print(f"  unsupported (scope+invalid):  {n_unsupported:>10,}  ({O2:.2f}% = O2)")
print(f"  supported:                    {n_supported:>10,}  ({Q2:.2f}% = Q2)")
print(
    f"    success:                    {n_success:>10,}  ({Q1:.4f}% of supported = Q1)"
)
print(f"    unconvertable:              {n_unconvertable:>10,}  (Q4)")
print(f"    unexpected (bugs):          {n_unexpected:>10,}")
print(f"    unavailable (data gap):     {n_unavailable:>10,}")
print(f"    runtime (accounting only):  {n_runtime:>10,}")

total wheels in main.db.wheel:    12,344,726
  yanked:                           118,637  (0.96% -- excluded from all % below; reroll_convert never attempts these by design)
  not yet attempted:                     0  (0.00% -- excluded from all % below)
attempted:                        12,226,089
  unsupported (scope+invalid):   1,686,892  (13.80% = O2)
  supported:                    10,539,197  (86.20% = Q2)
    success:                    10,527,661  (99.8905% of supported = Q1)
    unconvertable:                  11,225  (Q4)
    unexpected (bugs):                  37
    unavailable (data gap):            274
    runtime (accounting only):           0

### Q3: what makes up the {O2}% of "unsupported" wheels

`scope` (deliberate policy exclusions) + `invalid` (malformed wheel/metadata) errors,
broken into exception-type sub-buckets. `main.db.reroll_errors.category`/`.sub_category`
are already split columns (`sub_category` is the raising exception's class name), so
this is a plain `GROUP BY category, sub_category` over the ~1.7M-row `scope`/`invalid`
slice of `reroll_errors` -- no more regex/UDF parsing of a combined `"{category}:
{ExcType}: {message}"` text column, unlike the legacy
`v.db.repodata_conversion.reroll_error` this replaced.

In [31]:
scope_invalid_types = query_main(
    """
    SELECT category, sub_category AS exc_type, COUNT(*) AS n
    FROM reroll_errors
    WHERE category IN ('scope', 'invalid')
    GROUP BY category, exc_type
    ORDER BY n DESC
    """
)
scope_invalid_types["pct_of_attempted"] = (
    scope_invalid_types["n"] / attempted * 100
).round(3)
print(f"sum of n: {scope_invalid_types['n'].sum():,} (should equal {n_unsupported:,})")
scope_invalid_types

sum of n: 1,686,892 (should equal 1,686,892)

   category                            exc_type        n  pct_of_attempted
0     scope            UnsupportedPlatformError  1170766             9.576
1   invalid          InvalidInterpreterTagError   267715             2.190
2     scope         UnsupportedInterpreterError   177698             1.453
3   invalid            PythonRangeMismatchError    30068             0.246
4   invalid  InvalidPythonRequirementRangeError    24708             0.202
5   invalid             InvalidRequirementError     7044             0.058
6     scope  UnsupportedInterpreterVersionError     5288             0.043
7   invalid       MetadataFilenameMismatchError     1301             0.011
8   invalid                  InvalidAbiTagError     1031             0.008
9   invalid        InvalidVersionSpecifierError      986             0.008
10  invalid                InvalidFilenameError      234             0.002
11  invalid                InvalidMetadataError       53             0.000

In [32]:
# One representative message per exc_type, to write accurate human
# descriptions for the Q3 table. sub_category/description are already real
# columns, so this is a plain window-function pass -- no UDF needed.
samples = query_main(
    """
    WITH ranked AS (
        SELECT
            sub_category AS exc_type,
            description AS reroll_error,
            ROW_NUMBER() OVER (PARTITION BY sub_category ORDER BY wheel_id) AS rn
        FROM reroll_errors
        WHERE category IN ('scope', 'invalid')
    )
    SELECT exc_type, reroll_error FROM ranked WHERE rn = 1
    """
)
pd.set_option("display.max_colwidth", 300)
samples

,exc_type,reroll_error
0,InvalidAbiTagError,invalid abi tag: 'py3'
1,InvalidFilenameError,unparseable wheel filename '101903751_topsis-py3-none-any.whl': Invalid wheel filename (wrong number of parts): '101903751_topsis-py3-none-any'
2,InvalidInterpreterTagError,invalid interpreter tag: 'pp37'
3,InvalidMetadataError,"invalid METADATA: 1 validation error for WheelMetadata\nversion\n Value error, Invalid version: '0.2.1.Perceval' [type=value_error, input_value='0.2.1.Perceval', input_type=str]\n For further information visit https://errors.pydantic.dev/2.13/v/value_error"
4,InvalidPythonRequirementRangeError,not a contiguous Python 3.x minor range: ==2.7
5,InvalidRequirementError,"invalid requirement 'python-slugify (==4.0.1requests==2.24.0)': Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier\n python-slugify (==4.0.1requests==2.24.0)\n ~~~~~~~~~^"
6,InvalidVersionSpecifierError,invalid version specifier '>-3.6': Invalid specifier: '>-3.6'
7,MetadataFilenameMismatchError,METADATA Name/Version ('aksharajaana' 0.1.9.3) does not match filename 'AksharaJaana-0.1.9.4-py3-none-any.whl' ('aksharajaana' 0.1.9.4)
8,PythonRangeMismatchError,"csf-3dfin: filename-implied python range '~=3.14' does not intersect Requires-Python '<3.14,>=3.10'"
9,UnsupportedInterpreterError,unsupported interpreter major version: 'py2'
10,UnsupportedInterpreterVersionError,CPython < 3.4 is unsupported: 'cp33'
11,UnsupportedPlatformError,unsupported platform tag: 'win32'

In [33]:
for _, row in samples.iterrows():
    print(f"=== {row['exc_type']} ===")
    print(row["reroll_error"])
    print()

=== InvalidAbiTagError ===
invalid abi tag: 'py3'

=== InvalidFilenameError ===
unparseable wheel filename '101903751_topsis-py3-none-any.whl': Invalid wheel filename (wrong number of parts): '101903751_topsi
s-py3-none-any'

=== InvalidInterpreterTagError ===
invalid interpreter tag: 'pp37'

=== InvalidMetadataError ===
invalid METADATA: 1 validation error for WheelMetadata
version
  Value error, Invalid version: '0.2.1.Perceval' [type=value_error, input_value='0.2.1.Perceval', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error

=== InvalidPythonRequirementRangeError ===
not a contiguous Python 3.x minor range: ==2.7

=== InvalidRequirementError ===
invalid requirement 'python-slugify (==4.0.1requests==2.24.0)': Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after
version specifier
    python-slugify (==4.0.1requests==2.24.0)
                   ~~~~~~~~~^

=== InvalidVersionSpecifierError ===
invalid version specifier '>-3.6': Invalid specifier: '>-3.6'

=== MetadataFilenameMismatchError ===
METADATA Name/Version ('aksharajaana' 0.1.9.3) does not match filename 'AksharaJaana-0.1.9.4-py3-none-any.whl' ('aksharajaana' 0
.1.9.4)

=== PythonRangeMismatchError ===
csf-3dfin: filename-implied python range '~=3.14' does not intersect Requires-Python '<3.14,>=3.10'

=== UnsupportedInterpreterError ===
unsupported interpreter major version: 'py2'

=== UnsupportedInterpreterVersionError ===
CPython < 3.4 is unsupported: 'cp33'

=== UnsupportedPlatformError ===
unsupported platform tag: 'win32'

### Q3 table: human descriptions for each unsupported sub-bucket

One representative `reroll_error` message per exc_type (above) is enough to
write an accurate one-line description for each -- no further sampling
needed.

In [34]:
descriptions = {
    "UnsupportedPlatformError": "Wheel's platform tag is out of policy scope (e.g. musllinux, 32-bit Windows/Linux, iOS/Android, wasm, non-manylinux glibc, or an unsupported CPU arch)",
    "InvalidInterpreterTagError": "Wheel filename has a malformed/unrecognized interpreter tag (e.g. PyPy `pp37`)",
    "UnsupportedInterpreterError": "Wheel targets a non-CPython interpreter major (e.g. `py2`, no CPython tag at all)",
    "PythonRangeMismatchError": "Wheel filename's implied CPython version range doesn't intersect the sdist's declared `Requires-Python`",
    "InvalidPythonRequirementRangeError": "`Requires-Python` is not a contiguous Python 3.x minor-version range (e.g. `==2.7`)",
    "InvalidRequirementError": "A `Requires-Dist` entry fails to parse as a PEP 508 requirement string",
    "UnsupportedInterpreterVersionError": "Wheel targets CPython < 3.4 (below reroll's minimum supported version)",
    "MetadataFilenameMismatchError": "METADATA's Name/Version disagrees with the wheel filename's Name/Version",
    "InvalidVersionSpecifierError": "A version specifier fails to parse as PEP 440 (e.g. `>-3.6`)",
    "InvalidAbiTagError": "Wheel filename has a malformed/unrecognized ABI tag",
    "InvalidFilenameError": "Wheel filename doesn't parse at all (wrong number of `-`-separated parts, etc.)",
    "InvalidMetadataError": "METADATA fails pydantic validation (e.g. an unparseable `Version:` field)",
}

q3 = scope_invalid_types.copy()
q3["description"] = q3["exc_type"].map(descriptions)
q3 = q3[["category", "exc_type", "description", "n", "pct_of_attempted"]]
q3 = q3.sort_values("n", ascending=False).reset_index(drop=True)
print(
    f"O2 check: sum of pct_of_attempted = {q3['pct_of_attempted'].sum():.2f}% (O2 = {O2:.2f}%)"
)
q3

O2 check: sum of pct_of_attempted = 13.80% (O2 = 13.80%)

,category,exc_type,description,n,pct_of_attempted
0,scope,UnsupportedPlatformError,"Wheel's platform tag is out of policy scope (e.g. musllinux, 32-bit Windows/Linux, iOS/Android, wasm, non-manylinux glibc, or an unsupported CPU arch)",1170766,9.576
1,invalid,InvalidInterpreterTagError,Wheel filename has a malformed/unrecognized interpreter tag (e.g. PyPy `pp37`),267715,2.190
2,scope,UnsupportedInterpreterError,"Wheel targets a non-CPython interpreter major (e.g. `py2`, no CPython tag at all)",177698,1.453
3,invalid,PythonRangeMismatchError,Wheel filename's implied CPython version range doesn't intersect the sdist's declared `Requires-Python`,30068,0.246
4,invalid,InvalidPythonRequirementRangeError,`Requires-Python` is not a contiguous Python 3.x minor-version range (e.g. `==2.7`),24708,0.202
5,invalid,InvalidRequirementError,A `Requires-Dist` entry fails to parse as a PEP 508 requirement string,7044,0.058
6,scope,UnsupportedInterpreterVersionError,Wheel targets CPython < 3.4 (below reroll's minimum supported version),5288,0.043
7,invalid,MetadataFilenameMismatchError,METADATA's Name/Version disagrees with the wheel filename's Name/Version,1301,0.011
8,invalid,InvalidAbiTagError,Wheel filename has a malformed/unrecognized ABI tag,1031,0.008
9,invalid,InvalidVersionSpecifierError,A version specifier fails to parse as PEP 440 (e.g. `>-3.6`),986,0.008
10,invalid,InvalidFilenameError,"Wheel filename doesn't parse at all (wrong number of `-`-separated parts, etc.)",234,0.002
11,invalid,InvalidMetadataError,METADATA fails pydantic validation (e.g. an unparseable `Version:` field),53,0.000

### Q4 / Q5: the unconvertable bucket

Same targeted `category = 'unconvertable'` fetch (small population, cheap) as before,
now against `main.db.reroll_errors` -- rerun live rather than reusing copied-verbatim
counts, which go stale the moment the bucket's size or composition changes between
runs. It has, in fact, changed shape since the `v.db`-era classification: `main.db`'s
new curated-mapping gate (`reroll_data.reroll_convert`'s `MissingPypiCondaStaticMapping`,
a `RerollUnconvertableError` subclass for a dependency name reroll's live mapper chain
resolved but that no human has yet curated into `main.db.pypi_conda_names`) is now the
single largest `unconvertable` sub-bucket, and did not exist at all in the old
classification.

In [35]:
# Load the full "unconvertable" bucket live (small population -- a targeted
# fetch, not a scan of the 12.3M-row wheel table) and re-run the same
# classification regexes `reroll_v0.2.0_unconvertable_analysis.ipynb`
# established, now against the already-split sub_category/description
# columns instead of a combined "unconvertable: <ExcType>: <message>" text
# column -- no exc_type-extraction regex needed anymore.
unconvertable_df = query_main(
    "SELECT wheel_id, sub_category AS exc_type, description AS reroll_error "
    "FROM reroll_errors WHERE category = 'unconvertable'"
)

# UnconvertableRequirementError sub-buckets
req_errs = unconvertable_df[
    unconvertable_df["exc_type"] == "UnconvertableRequirementError"
].copy()


def classify_req_error(msg):
    m = re.search(r"cannot convert '[^']*':\s*(.+)$", msg)
    if m:
        return m.group(1)
    m = re.search(r"is not a legal conda extra name \(CEP-29\):\s*(.+)$", msg)
    if m:
        return f"illegal conda extra name: {m.group(1)}"
    return "OTHER/unrecognized"


req_errs["reason_template"] = (
    req_errs["reroll_error"]
    .map(classify_req_error)
    .str.replace(r"'[^']*'", "<LIT>", regex=True)
    .str.replace(r"\b\d+(?:\.\d+)*\b", "<NUM>", regex=True)
)
req_sub = req_errs["reason_template"].value_counts()

# UnconvertableMarkerError sub-buckets
marker_errs = unconvertable_df[
    unconvertable_df["exc_type"] == "UnconvertableMarkerError"
].copy()
unpermitted = marker_errs["reroll_error"].str.extract(
    r"unpermitted key\(s\) \['([^']*)'"
)[0]


def bucket_marker(msg, key):
    if pd.notna(key):
        return "unpermitted key"
    if "markers are not supported" in msg:
        return "'in'/'not in' marker unsupported"
    if "not a valid version" in msg:
        return "python_version literal not a valid version"
    if "is not supported for" in msg:
        return "unsupported comparator (~=) for python_version(_full)"
    if "not a plain major.minor" in msg:
        return "python_version literal not major.minor precision"
    return "OTHER/unrecognized"


marker_errs["bucket"] = [
    bucket_marker(m, k) for m, k in zip(marker_errs["reroll_error"], unpermitted)
]
marker_sub = marker_errs["bucket"].value_counts()

# UnresolvedCondaNameError sub-buckets
unres = unconvertable_df[
    unconvertable_df["exc_type"] == "UnresolvedCondaNameError"
].copy()
unres["dep_name"] = unres["reroll_error"].str.extract(
    r"no mapper resolved a conda name for '([^']*)'"
)[0]
unres_sub = unres["dep_name"].value_counts()

# InvalidCondaNameError sub-buckets
invalid_errs = unconvertable_df[unconvertable_df["exc_type"] == "InvalidCondaNameError"]
n_long_names = invalid_errs["reroll_error"].str.contains("exceeds 64 characters").sum()
n_homoglyph = len(invalid_errs) - n_long_names

n_pyver_eq = (
    unconvertable_df["exc_type"] == "UnconvertablePythonVersionEqualityError"
).sum()

# MissingPypiCondaStaticMapping -- new in the db2 schema, does not appear in
# any v.db-era snapshot: reroll_data.reroll_convert's curated-mapping gate
# rejects a wheel whose live mapper chain resolved a dependency name reroll
# has not yet had a human curate into main.db.pypi_conda_names (see that
# module's docstring, "The new mapper" section). No further
# sub-classification needed -- description is already specific (one
# unresolved pypi name per row).
n_missing_static = int(
    (unconvertable_df["exc_type"] == "MissingPypiCondaStaticMapping").sum()
)

q5_rows = [
    (
        "MissingPypiCondaStaticMapping",
        "dependency name reroll's live mapper chain resolved, but no human has curated it into main.db.pypi_conda_names yet",
        n_missing_static,
    ),
    (
        "UnconvertableRequirementError",
        "PEP 440 local version label (torch/ipex-llm/vllm-cpu +cpu/+xpu hardware variants)",
        int(
            req_sub.get(
                "cannot convert specifier <LIT>: it has a local version label", 0
            )
        ),
    ),
    (
        "InvalidCondaNameError",
        "name >64 chars (SEO-spam PyPI project names)",
        int(n_long_names),
    ),
    (
        "UnconvertableRequirementError",
        "illegal conda extra name (CEP-29)",
        int(
            req_sub.get(
                "illegal conda extra name: must be <NUM>-<NUM> characters of [a-z0-9_.+-]",
                0,
            )
        ),
    ),
    (
        "UnconvertableMarkerError",
        "unsupported comparator (~=) for python_version(_full)",
        int(marker_sub.get("unsupported comparator (~=) for python_version(_full)", 0)),
    ),
    (
        "UnconvertableMarkerError",
        "python_version literal not a valid version (e.g. '2.7.*', '3.x', 'dev')",
        int(marker_sub.get("python_version literal not a valid version", 0)),
    ),
    (
        "UnconvertableMarkerError",
        "unpermitted key (platform_release/_version/_machine/sys_platform/platform_python_implementation)",
        int(marker_sub.get("unpermitted key", 0)),
    ),
    (
        "UnconvertableRequirementError",
        "amulet-compiler-version numeric-overflow version",
        int(req_sub.get("OTHER/unrecognized", 0)),
    ),
    (
        "UnconvertableMarkerError",
        "python_version literal not major.minor precision",
        int(marker_sub.get("python_version literal not major.minor precision", 0)),
    ),
    (
        "UnconvertableMarkerError",
        "'in'/'not in' marker unsupported",
        int(marker_sub.get("'in'/'not in' marker unsupported", 0)),
    ),
    (
        "UnconvertablePythonVersionEqualityError",
        "python_version ==/!= a non-major.minor literal",
        int(n_pyver_eq),
    ),
    (
        "UnconvertableRequirementError",
        "direct URL reference",
        int(req_sub.get("it has a direct URL reference", 0)),
    ),
    (
        "UnresolvedCondaNameError",
        f"{len(unres_sub)} unresolved dep names ({', '.join(unres_sub.index)})",
        int(unres_sub.sum()),
    ),
    (
        "InvalidCondaNameError",
        "homoglyph/Cyrillic lookalike name (e.g. `tаamo`)",
        int(n_homoglyph),
    ),
]
q5 = pd.DataFrame(q5_rows, columns=["exc_type", "description", "n"])
q5 = q5[q5["n"] > 0].sort_values("n", ascending=False).reset_index(drop=True)

assert q5["n"].sum() == n_unconvertable == Q4, (q5["n"].sum(), n_unconvertable, Q4)
q5["pct_of_supported"] = (q5["n"] / n_supported * 100).round(3)
print(f"Q4 = {Q4:,} rows")
print(
    f"sum of pct_of_supported = {q5['pct_of_supported'].sum():.2f}% "
    f"(should equal Q4/n_supported = {Q4 / n_supported * 100:.2f}%)"
)
q5

Q4 = 11,225 rows
sum of pct_of_supported = 0.11% (should equal Q4/n_supported = 0.11%)

,exc_type,description,n,pct_of_supported
0,UnconvertableRequirementError,PEP 440 local version label (torch/ipex-llm/vllm-cpu +cpu/+xpu hardware variants),6382,0.061
1,InvalidCondaNameError,name >64 chars (SEO-spam PyPI project names),1276,0.012
2,UnconvertableRequirementError,illegal conda extra name (CEP-29),672,0.006
3,UnconvertableMarkerError,unsupported comparator (~=) for python_version(_full),640,0.006
4,UnconvertableMarkerError,"python_version literal not a valid version (e.g. '2.7.*', '3.x', 'dev')",590,0.006
5,UnconvertableMarkerError,unpermitted key (platform_release/_version/_machine/sys_platform/platform_python_implementation),502,0.005
6,UnconvertableRequirementError,amulet-compiler-version numeric-overflow version,426,0.004
7,UnconvertableMarkerError,python_version literal not major.minor precision,240,0.002
8,UnconvertableMarkerError,'in'/'not in' marker unsupported,230,0.002
9,UnconvertablePythonVersionEqualityError,python_version ==/!= a non-major.minor literal,142,0.001
10,UnconvertableRequirementError,direct URL reference,89,0.001
11,UnresolvedCondaNameError,"4 unresolved dep names (alchemiscale, oasis, nr-config, sktools)",34,0.000
12,InvalidCondaNameError,homoglyph/Cyrillic lookalike name (e.g. `tаamo`),2,0.000